flowchart LR
  consensus_core --> mysten_common
  consensus_core --> mysten_metrics
  consensus_core --> mysten_network
  consensus_core --> shared_crypto
  consensus_core --> sui_protocol_config
  consensus_core --> telemetry_subscribers
  consensus_core --> typed_store
  mysten_common --> mysten_metrics
  mysten_network --> mysten_metrics
  mysten_service --> mysten_metrics
  mysten_service --> telemetry_subscribers
  sui_adapter_latest --> mysten_common
  sui_adapter_latest --> mysten_metrics
  sui_adapter_latest --> sui_protocol_config
  sui_adapter_latest --> sui_types
  sui_config --> mysten_common
  sui_config --> sui_protocol_config
  sui_config --> sui_types
  sui_core --> consensus_core
  sui_core --> mysten_common
  sui_core --> mysten_metrics
  sui_core --> mysten_network
  sui_core --> shared_crypto
  sui_core --> sui_config
  sui_core --> sui_execution
  sui_core --> sui_json_rpc_types
  sui_core --> sui_network
  sui_core --> sui_protocol_config
  sui_core --> sui_storage
  sui_core --> sui_types
  sui_core --> telemetry_subscribers
  sui_core --> typed_store
  sui_execution --> sui_adapter_latest
  sui_execution --> sui_protocol_config
  sui_execution --> sui_types
  sui_json_rpc --> mysten_metrics
  sui_json_rpc --> shared_crypto
  sui_json_rpc --> sui_config
  sui_json_rpc --> sui_core
  sui_json_rpc --> sui_json_rpc_api
  sui_json_rpc --> sui_json_rpc_types
  sui_json_rpc --> sui_protocol_config
  sui_json_rpc --> sui_storage
  sui_json_rpc --> sui_types
  sui_json_rpc --> telemetry_subscribers
  sui_json_rpc_api --> mysten_metrics
  sui_json_rpc_api --> sui_json_rpc_types
  sui_json_rpc_api --> sui_types
  sui_json_rpc_types --> mysten_metrics
  sui_json_rpc_types --> sui_protocol_config
  sui_json_rpc_types --> sui_types
  sui_network --> mysten_common
  sui_network --> mysten_metrics
  sui_network --> mysten_network
  sui_network --> shared_crypto
  sui_network --> sui_config
  sui_network --> sui_protocol_config
  sui_network --> sui_storage
  sui_network --> sui_types
  sui_network --> telemetry_subscribers
  sui_node --> consensus_core
  sui_node --> mysten_common
  sui_node --> mysten_metrics
  sui_node --> mysten_network
  sui_node --> mysten_service
  sui_node --> sui_config
  sui_node --> sui_core
  sui_node --> sui_json_rpc
  sui_node --> sui_json_rpc_api
  sui_node --> sui_network
  sui_node --> sui_protocol_config
  sui_node --> sui_storage
  sui_node --> sui_types
  sui_node --> telemetry_subscribers
  sui_node --> typed_store
  sui_storage --> mysten_metrics
  sui_storage --> sui_config
  sui_storage --> sui_json_rpc_types
  sui_storage --> sui_protocol_config
  sui_storage --> sui_types
  sui_storage --> telemetry_subscribers
  sui_storage --> typed_store
  sui_types --> mysten_common
  sui_types --> mysten_metrics
  sui_types --> mysten_network
  sui_types --> shared_crypto
  sui_types --> sui_protocol_config
  typed_store --> mysten_common
  typed_store --> mysten_metrics
