flowchart LR
  consensus-core --> mysten-common
  consensus-core --> mysten-metrics
  consensus-core --> mysten-network
  consensus-core --> shared-crypto
  consensus-core --> sui-protocol-config
  consensus-core --> telemetry-subscribers
  consensus-core --> typed-store
  mysten-common --> mysten-metrics
  mysten-network --> mysten-metrics
  mysten-service --> mysten-metrics
  mysten-service --> telemetry-subscribers
  sui-adapter-latest --> mysten-common
  sui-adapter-latest --> mysten-metrics
  sui-adapter-latest --> sui-protocol-config
  sui-adapter-latest --> sui-types
  sui-config --> mysten-common
  sui-config --> sui-protocol-config
  sui-config --> sui-types
  sui-core --> consensus-core
  sui-core --> mysten-common
  sui-core --> mysten-metrics
  sui-core --> mysten-network
  sui-core --> shared-crypto
  sui-core --> sui-config
  sui-core --> sui-execution
  sui-core --> sui-json-rpc-types
  sui-core --> sui-network
  sui-core --> sui-protocol-config
  sui-core --> sui-storage
  sui-core --> sui-types
  sui-core --> telemetry-subscribers
  sui-core --> typed-store
  sui-execution --> sui-adapter-latest
  sui-execution --> sui-protocol-config
  sui-execution --> sui-types
  sui-json-rpc --> mysten-metrics
  sui-json-rpc --> shared-crypto
  sui-json-rpc --> sui-config
  sui-json-rpc --> sui-core
  sui-json-rpc --> sui-json-rpc-api
  sui-json-rpc --> sui-json-rpc-types
  sui-json-rpc --> sui-protocol-config
  sui-json-rpc --> sui-storage
  sui-json-rpc --> sui-types
  sui-json-rpc --> telemetry-subscribers
  sui-json-rpc-api --> mysten-metrics
  sui-json-rpc-api --> sui-json-rpc-types
  sui-json-rpc-api --> sui-types
  sui-json-rpc-types --> mysten-metrics
  sui-json-rpc-types --> sui-protocol-config
  sui-json-rpc-types --> sui-types
  sui-network --> mysten-common
  sui-network --> mysten-metrics
  sui-network --> mysten-network
  sui-network --> shared-crypto
  sui-network --> sui-config
  sui-network --> sui-protocol-config
  sui-network --> sui-storage
  sui-network --> sui-types
  sui-network --> telemetry-subscribers
  sui-node --> consensus-core
  sui-node --> mysten-common
  sui-node --> mysten-metrics
  sui-node --> mysten-network
  sui-node --> mysten-service
  sui-node --> sui-config
  sui-node --> sui-core
  sui-node --> sui-json-rpc
  sui-node --> sui-json-rpc-api
  sui-node --> sui-network
  sui-node --> sui-protocol-config
  sui-node --> sui-storage
  sui-node --> sui-types
  sui-node --> telemetry-subscribers
  sui-node --> typed-store
  sui-storage --> mysten-metrics
  sui-storage --> sui-config
  sui-storage --> sui-json-rpc-types
  sui-storage --> sui-protocol-config
  sui-storage --> sui-types
  sui-storage --> telemetry-subscribers
  sui-storage --> typed-store
  sui-types --> mysten-common
  sui-types --> mysten-metrics
  sui-types --> mysten-network
  sui-types --> shared-crypto
  sui-types --> sui-protocol-config
  typed-store --> mysten-common
  typed-store --> mysten-metrics
