flowchart LR
  sui["sui(277)"] --> move["move"]
  sui["sui(111)"] --> other["other"]
  other["other(68)"] --> move["move"]
  sui["sui(56)"] --> mysten["mysten"]
  other["other(49)"] --> sui["sui"]
  consensus["consensus(9)"] --> sui["sui"]
  sui["sui(9)"] --> typed_store["typed_store"]
  sui["sui(8)"] --> consensus["consensus"]
  consensus["consensus(6)"] --> mysten["mysten"]
  move["move(4)"] --> other["other"]
  consensus["consensus(4)"] --> other["other"]
  other["other(4)"] --> mysten["mysten"]
  mysten["mysten(3)"] --> sui["sui"]
  other["other(3)"] --> consensus["consensus"]
  consensus["consensus(2)"] --> typed_store["typed_store"]
  mysten["mysten(2)"] --> other["other"]
  typed_store["typed_store(2)"] --> mysten["mysten"]
  typed_store["typed_store(1)"] --> sui["sui"]
