flowchart LR
  consensus-config --> mysten-network
  consensus-core --> consensus-config
  consensus-core --> consensus-types
  consensus-core --> mysten-common
  consensus-core --> mysten-metrics
  consensus-core --> mysten-network
  consensus-core --> sui-http
  consensus-core --> sui-macros
  consensus-core --> sui-protocol-config
  consensus-core --> sui-tls
  consensus-core --> typed-store
  consensus-framework --> consensus-config
  consensus-framework --> consensus-core
  consensus-framework --> consensus-types
  consensus-framework --> sui-types
  consensus-simtests --> consensus-config
  consensus-simtests --> consensus-core
  consensus-simtests --> consensus-types
  consensus-simtests --> mysten-metrics
  consensus-simtests --> mysten-network
  consensus-simtests --> sui-config
  consensus-simtests --> sui-macros
  consensus-simtests --> sui-protocol-config
  consensus-simtests --> sui-simulator
  consensus-simtests --> typed-store
  consensus-study --> consensus-config
  consensus-study --> consensus-core
  consensus-study --> consensus-types
  consensus-types --> consensus-config
  mysten-common --> mysten-metrics
  mysten-common --> sui-macros
  mysten-network --> mysten-metrics
  mysten-network --> sui-http
  mysten-network --> sui-tls
  mysten-service --> mysten-metrics
  sui --> mysten-common
  sui --> sui-bridge
  sui --> sui-config
  sui --> sui-data-store
  sui --> sui-execution
  sui --> sui-faucet
  sui --> sui-futures
  sui --> sui-genesis-builder
  sui --> sui-indexer-alt
  sui --> sui-indexer-alt-consistent-store
  sui --> sui-indexer-alt-framework
  sui --> sui-indexer-alt-graphql
  sui --> sui-indexer-alt-reader
  sui --> sui-json
  sui --> sui-json-rpc-types
  sui --> sui-keys
  sui --> sui-macros
  sui --> sui-move
  sui --> sui-move-build
  sui --> sui-package-alt
  sui --> sui-package-management
  sui --> sui-pg-db
  sui --> sui-protocol-config
  sui --> sui-replay-2
  sui --> sui-sdk
  sui --> sui-simulator
  sui --> sui-source-validation
  sui --> sui-swarm
  sui --> sui-swarm-config
  sui --> sui-test-transaction-builder
  sui --> sui-transaction-builder
  sui --> sui-types
  sui-adapter-latest --> mysten-common
  sui-adapter-latest --> mysten-metrics
  sui-adapter-latest --> sui-macros
  sui-adapter-latest --> sui-protocol-config
  sui-adapter-latest --> sui-types
  sui-adapter-transactional-tests --> sui-transactional-test-runner
  sui-adapter-v0 --> sui-macros
  sui-adapter-v0 --> sui-protocol-config
  sui-adapter-v0 --> sui-types
  sui-adapter-v1 --> sui-macros
  sui-adapter-v1 --> sui-protocol-config
  sui-adapter-v1 --> sui-types
  sui-adapter-v2 --> sui-macros
  sui-adapter-v2 --> sui-protocol-config
  sui-adapter-v2 --> sui-types
  sui-analytics-indexer --> mysten-metrics
  sui-analytics-indexer --> sui-analytics-indexer-derive
  sui-analytics-indexer --> sui-futures
  sui-analytics-indexer --> sui-indexer
  sui-analytics-indexer --> sui-indexer-alt-framework
  sui-analytics-indexer --> sui-indexer-alt-framework-store-traits
  sui-analytics-indexer --> sui-indexer-alt-metrics
  sui-analytics-indexer --> sui-indexer-alt-object-store
  sui-analytics-indexer --> sui-json-rpc-types
  sui-analytics-indexer --> sui-package-resolver
  sui-analytics-indexer --> sui-rpc-api
  sui-analytics-indexer --> sui-storage
  sui-analytics-indexer --> sui-types
  sui-analytics-indexer --> typed-store
  sui-authority-aggregation --> mysten-metrics
  sui-authority-aggregation --> sui-types
  sui-aws-orchestrator --> mysten-metrics
  sui-aws-orchestrator --> sui-config
  sui-aws-orchestrator --> sui-swarm-config
  sui-aws-orchestrator --> sui-types
  sui-benchmark --> mysten-metrics
  sui-benchmark --> sui-config
  sui-benchmark --> sui-core
  sui-benchmark --> sui-json-rpc-types
  sui-benchmark --> sui-keys
  sui-benchmark --> sui-move-build
  sui-benchmark --> sui-network
  sui-benchmark --> sui-protocol-config
  sui-benchmark --> sui-sdk
  sui-benchmark --> sui-storage
  sui-benchmark --> sui-surfer
  sui-benchmark --> sui-swarm-config
  sui-benchmark --> sui-test-transaction-builder
  sui-benchmark --> sui-types
  sui-bridge --> mysten-common
  sui-bridge --> mysten-metrics
  sui-bridge --> sui-authority-aggregation
  sui-bridge --> sui-config
  sui-bridge --> sui-json-rpc-api
  sui-bridge --> sui-json-rpc-types
  sui-bridge --> sui-keys
  sui-bridge --> sui-metrics-push-client
  sui-bridge --> sui-sdk
  sui-bridge --> sui-test-transaction-builder
  sui-bridge --> sui-types
  sui-bridge --> typed-store
  sui-bridge-cli --> sui-bridge
  sui-bridge-cli --> sui-config
  sui-bridge-cli --> sui-json-rpc-types
  sui-bridge-cli --> sui-keys
  sui-bridge-cli --> sui-sdk
  sui-bridge-cli --> sui-types
  sui-bridge-indexer --> mysten-metrics
  sui-bridge-indexer --> sui-bridge
  sui-bridge-indexer --> sui-bridge-schema
  sui-bridge-indexer --> sui-config
  sui-bridge-indexer --> sui-data-ingestion-core
  sui-bridge-indexer --> sui-indexer
  sui-bridge-indexer --> sui-indexer-builder
  sui-bridge-indexer --> sui-json-rpc-types
  sui-bridge-indexer --> sui-pg-db
  sui-bridge-indexer --> sui-sdk
  sui-bridge-indexer --> sui-test-transaction-builder
  sui-bridge-indexer --> sui-types
  sui-bridge-indexer-alt --> mysten-metrics
  sui-bridge-indexer-alt --> sui-bridge
  sui-bridge-indexer-alt --> sui-bridge-schema
  sui-bridge-indexer-alt --> sui-indexer-alt-framework
  sui-bridge-indexer-alt --> sui-indexer-alt-metrics
  sui-bridge-schema --> sui-field-count
  sui-bridge-schema --> sui-indexer-builder
  sui-checkpoint-blob-indexer --> sui-config
  sui-checkpoint-blob-indexer --> sui-indexer-alt-framework
  sui-checkpoint-blob-indexer --> sui-indexer-alt-framework-store-traits
  sui-checkpoint-blob-indexer --> sui-indexer-alt-metrics
  sui-checkpoint-blob-indexer --> sui-indexer-alt-object-store
  sui-checkpoint-blob-indexer --> sui-types
  sui-cluster-test --> sui-config
  sui-cluster-test --> sui-core
  sui-cluster-test --> sui-faucet
  sui-cluster-test --> sui-graphql-rpc
  sui-cluster-test --> sui-indexer
  sui-cluster-test --> sui-json
  sui-cluster-test --> sui-json-rpc-types
  sui-cluster-test --> sui-keys
  sui-cluster-test --> sui-move-build
  sui-cluster-test --> sui-pg-db
  sui-cluster-test --> sui-sdk
  sui-cluster-test --> sui-swarm
  sui-cluster-test --> sui-swarm-config
  sui-cluster-test --> sui-test-transaction-builder
  sui-cluster-test --> sui-types
  sui-config --> consensus-config
  sui-config --> mysten-common
  sui-config --> sui-keys
  sui-config --> sui-protocol-config
  sui-config --> sui-types
  sui-core --> consensus-config
  sui-core --> consensus-core
  sui-core --> consensus-types
  sui-core --> mysten-common
  sui-core --> mysten-metrics
  sui-core --> mysten-network
  sui-core --> sui-authority-aggregation
  sui-core --> sui-config
  sui-core --> sui-execution
  sui-core --> sui-framework
  sui-core --> sui-genesis-builder
  sui-core --> sui-json-rpc-types
  sui-core --> sui-macros
  sui-core --> sui-move
  sui-core --> sui-move-build
  sui-core --> sui-network
  sui-core --> sui-protocol-config
  sui-core --> sui-simulator
  sui-core --> sui-storage
  sui-core --> sui-swarm-config
  sui-core --> sui-test-transaction-builder
  sui-core --> sui-tls
  sui-core --> sui-transaction-checks
  sui-core --> sui-types
  sui-core --> typed-store
  sui-cost --> sui-config
  sui-cost --> sui-json-rpc-types
  sui-cost --> sui-move-build
  sui-cost --> sui-swarm-config
  sui-cost --> sui-test-transaction-builder
  sui-cost --> sui-types
  sui-data-ingestion --> mysten-metrics
  sui-data-ingestion --> sui-data-ingestion-core
  sui-data-ingestion --> sui-kvstore
  sui-data-ingestion --> sui-storage
  sui-data-ingestion --> sui-types
  sui-data-ingestion-core --> mysten-metrics
  sui-data-ingestion-core --> sui-protocol-config
  sui-data-ingestion-core --> sui-rpc-api
  sui-data-ingestion-core --> sui-storage
  sui-data-ingestion-core --> sui-types
  sui-data-store --> sui-config
  sui-data-store --> sui-types
  sui-deepbook-indexer --> mysten-metrics
  sui-deepbook-indexer --> sui-config
  sui-deepbook-indexer --> sui-data-ingestion-core
  sui-deepbook-indexer --> sui-indexer-builder
  sui-deepbook-indexer --> sui-json-rpc-types
  sui-deepbook-indexer --> sui-sdk
  sui-deepbook-indexer --> sui-types
  sui-display --> sui-json-rpc-types
  sui-display --> sui-types
  sui-e2e-tests --> mysten-common
  sui-e2e-tests --> mysten-metrics
  sui-e2e-tests --> sui-config
  sui-e2e-tests --> sui-core
  sui-e2e-tests --> sui-framework
  sui-e2e-tests --> sui-framework-snapshot
  sui-e2e-tests --> sui-json-rpc
  sui-e2e-tests --> sui-json-rpc-api
  sui-e2e-tests --> sui-json-rpc-types
  sui-e2e-tests --> sui-keys
  sui-e2e-tests --> sui-light-client
  sui-e2e-tests --> sui-macros
  sui-e2e-tests --> sui-move-build
  sui-e2e-tests --> sui-network
  sui-e2e-tests --> sui-node
  sui-e2e-tests --> sui-protocol-config
  sui-e2e-tests --> sui-rpc-api
  sui-e2e-tests --> sui-sdk
  sui-e2e-tests --> sui-simulator
  sui-e2e-tests --> sui-storage
  sui-e2e-tests --> sui-swarm
  sui-e2e-tests --> sui-swarm-config
  sui-e2e-tests --> sui-test-transaction-builder
  sui-e2e-tests --> sui-tool
  sui-e2e-tests --> sui-types
  sui-execution --> sui-adapter-latest
  sui-execution --> sui-adapter-v0
  sui-execution --> sui-adapter-v1
  sui-execution --> sui-adapter-v2
  sui-execution --> sui-move-natives-latest
  sui-execution --> sui-move-natives-v0
  sui-execution --> sui-move-natives-v1
  sui-execution --> sui-move-natives-v2
  sui-execution --> sui-protocol-config
  sui-execution --> sui-types
  sui-execution --> sui-verifier-latest
  sui-execution --> sui-verifier-v0
  sui-execution --> sui-verifier-v1
  sui-execution --> sui-verifier-v2
  sui-faucet --> sui-config
  sui-faucet --> sui-keys
  sui-faucet --> sui-sdk
  sui-field-count --> sui-field-count-derive
  sui-framework --> sui-config
  sui-framework --> sui-move-build
  sui-framework --> sui-package-alt
  sui-framework --> sui-types
  sui-framework-snapshot --> sui-framework
  sui-framework-snapshot --> sui-move-build
  sui-framework-snapshot --> sui-protocol-config
  sui-framework-snapshot --> sui-types
  sui-framework-tests --> sui-config
  sui-framework-tests --> sui-framework
  sui-framework-tests --> sui-move
  sui-framework-tests --> sui-move-build
  sui-framework-tests --> sui-protocol-config
  sui-framework-tests --> sui-types
  sui-genesis-builder --> sui-config
  sui-genesis-builder --> sui-execution
  sui-genesis-builder --> sui-framework
  sui-genesis-builder --> sui-framework-snapshot
  sui-genesis-builder --> sui-protocol-config
  sui-genesis-builder --> sui-types
  sui-graphql-e2e-tests --> sui-graphql-rpc
  sui-graphql-e2e-tests --> sui-transactional-test-runner
  sui-graphql-rpc --> mysten-metrics
  sui-graphql-rpc --> mysten-network
  sui-graphql-rpc --> sui-default-config
  sui-graphql-rpc --> sui-display
  sui-graphql-rpc --> sui-framework
  sui-graphql-rpc --> sui-graphql-rpc-client
  sui-graphql-rpc --> sui-graphql-rpc-headers
  sui-graphql-rpc --> sui-indexer
  sui-graphql-rpc --> sui-json-rpc
  sui-graphql-rpc --> sui-json-rpc-types
  sui-graphql-rpc --> sui-move-build
  sui-graphql-rpc --> sui-name-service
  sui-graphql-rpc --> sui-package-resolver
  sui-graphql-rpc --> sui-pg-db
  sui-graphql-rpc --> sui-protocol-config
  sui-graphql-rpc --> sui-rpc-api
  sui-graphql-rpc --> sui-sdk
  sui-graphql-rpc --> sui-swarm-config
  sui-graphql-rpc --> sui-test-transaction-builder
  sui-graphql-rpc --> sui-types
  sui-graphql-rpc-client --> sui-graphql-rpc-headers
  sui-indexer --> mysten-metrics
  sui-indexer --> sui-config
  sui-indexer --> sui-core
  sui-indexer --> sui-data-ingestion-core
  sui-indexer --> sui-json
  sui-indexer --> sui-json-rpc
  sui-indexer --> sui-json-rpc-api
  sui-indexer --> sui-json-rpc-types
  sui-indexer --> sui-keys
  sui-indexer --> sui-move-build
  sui-indexer --> sui-name-service
  sui-indexer --> sui-open-rpc
  sui-indexer --> sui-package-resolver
  sui-indexer --> sui-pg-db
  sui-indexer --> sui-protocol-config
  sui-indexer --> sui-rpc-api
  sui-indexer --> sui-sdk
  sui-indexer --> sui-snapshot
  sui-indexer --> sui-storage
  sui-indexer --> sui-swarm-config
  sui-indexer --> sui-test-transaction-builder
  sui-indexer --> sui-transaction-builder
  sui-indexer --> sui-types
  sui-indexer-alt --> sui-default-config
  sui-indexer-alt --> sui-indexer-alt-framework
  sui-indexer-alt --> sui-indexer-alt-metrics
  sui-indexer-alt --> sui-indexer-alt-schema
  sui-indexer-alt --> sui-protocol-config
  sui-indexer-alt --> sui-synthetic-ingestion
  sui-indexer-alt --> sui-types
  sui-indexer-alt-consistent-store --> mysten-network
  sui-indexer-alt-consistent-store --> sui-default-config
  sui-indexer-alt-consistent-store --> sui-futures
  sui-indexer-alt-consistent-store --> sui-indexer-alt-consistent-api
  sui-indexer-alt-consistent-store --> sui-indexer-alt-framework
  sui-indexer-alt-consistent-store --> sui-indexer-alt-metrics
  sui-indexer-alt-consistent-store --> sui-storage
  sui-indexer-alt-e2e-tests --> sui-field-count
  sui-indexer-alt-e2e-tests --> sui-futures
  sui-indexer-alt-e2e-tests --> sui-indexer-alt
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-consistent-api
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-consistent-store
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-framework
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-graphql
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-jsonrpc
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-reader
  sui-indexer-alt-e2e-tests --> sui-indexer-alt-schema
  sui-indexer-alt-e2e-tests --> sui-json-rpc-types
  sui-indexer-alt-e2e-tests --> sui-macros
  sui-indexer-alt-e2e-tests --> sui-move-build
  sui-indexer-alt-e2e-tests --> sui-pg-db
  sui-indexer-alt-e2e-tests --> sui-sdk
  sui-indexer-alt-e2e-tests --> sui-storage
  sui-indexer-alt-e2e-tests --> sui-swarm-config
  sui-indexer-alt-e2e-tests --> sui-test-transaction-builder
  sui-indexer-alt-e2e-tests --> sui-transactional-test-runner
  sui-indexer-alt-e2e-tests --> sui-types
  sui-indexer-alt-framework --> sui-field-count
  sui-indexer-alt-framework --> sui-futures
  sui-indexer-alt-framework --> sui-indexer-alt-framework-store-traits
  sui-indexer-alt-framework --> sui-indexer-alt-metrics
  sui-indexer-alt-framework --> sui-pg-db
  sui-indexer-alt-framework --> sui-rpc-api
  sui-indexer-alt-framework --> sui-storage
  sui-indexer-alt-framework --> sui-synthetic-ingestion
  sui-indexer-alt-framework --> sui-types
  sui-indexer-alt-graphql --> sui-default-config
  sui-indexer-alt-graphql --> sui-display
  sui-indexer-alt-graphql --> sui-futures
  sui-indexer-alt-graphql --> sui-indexer-alt-metrics
  sui-indexer-alt-graphql --> sui-indexer-alt-reader
  sui-indexer-alt-graphql --> sui-indexer-alt-schema
  sui-indexer-alt-graphql --> sui-name-service
  sui-indexer-alt-graphql --> sui-package-resolver
  sui-indexer-alt-graphql --> sui-pg-db
  sui-indexer-alt-graphql --> sui-protocol-config
  sui-indexer-alt-graphql --> sui-rpc-api
  sui-indexer-alt-graphql --> sui-sql-macro
  sui-indexer-alt-graphql --> sui-types
  sui-indexer-alt-jsonrpc --> sui-default-config
  sui-indexer-alt-jsonrpc --> sui-display
  sui-indexer-alt-jsonrpc --> sui-futures
  sui-indexer-alt-jsonrpc --> sui-indexer-alt-metrics
  sui-indexer-alt-jsonrpc --> sui-indexer-alt-reader
  sui-indexer-alt-jsonrpc --> sui-indexer-alt-schema
  sui-indexer-alt-jsonrpc --> sui-json
  sui-indexer-alt-jsonrpc --> sui-json-rpc-api
  sui-indexer-alt-jsonrpc --> sui-json-rpc-types
  sui-indexer-alt-jsonrpc --> sui-name-service
  sui-indexer-alt-jsonrpc --> sui-open-rpc
  sui-indexer-alt-jsonrpc --> sui-open-rpc-macros
  sui-indexer-alt-jsonrpc --> sui-package-resolver
  sui-indexer-alt-jsonrpc --> sui-pg-db
  sui-indexer-alt-jsonrpc --> sui-protocol-config
  sui-indexer-alt-jsonrpc --> sui-sql-macro
  sui-indexer-alt-jsonrpc --> sui-types
  sui-indexer-alt-metrics --> sui-futures
  sui-indexer-alt-metrics --> sui-pg-db
  sui-indexer-alt-object-store --> sui-indexer-alt-framework-store-traits
  sui-indexer-alt-reader --> sui-futures
  sui-indexer-alt-reader --> sui-indexer-alt-consistent-api
  sui-indexer-alt-reader --> sui-indexer-alt-metrics
  sui-indexer-alt-reader --> sui-indexer-alt-schema
  sui-indexer-alt-reader --> sui-kvstore
  sui-indexer-alt-reader --> sui-package-resolver
  sui-indexer-alt-reader --> sui-pg-db
  sui-indexer-alt-reader --> sui-rpc-api
  sui-indexer-alt-reader --> sui-sql-macro
  sui-indexer-alt-reader --> sui-types
  sui-indexer-alt-restorer --> sui-config
  sui-indexer-alt-restorer --> sui-core
  sui-indexer-alt-restorer --> sui-data-ingestion-core
  sui-indexer-alt-restorer --> sui-field-count
  sui-indexer-alt-restorer --> sui-futures
  sui-indexer-alt-restorer --> sui-indexer-alt-schema
  sui-indexer-alt-restorer --> sui-pg-db
  sui-indexer-alt-restorer --> sui-snapshot
  sui-indexer-alt-restorer --> sui-storage
  sui-indexer-alt-restorer --> sui-types
  sui-indexer-alt-schema --> sui-field-count
  sui-indexer-alt-schema --> sui-protocol-config
  sui-indexer-alt-schema --> sui-types
  sui-indexer-builder --> mysten-metrics
  sui-indexer-builder --> sui-data-ingestion-core
  sui-indexer-builder --> sui-indexer-builder
  sui-indexer-builder --> sui-sdk
  sui-indexer-builder --> sui-types
  sui-json --> sui-framework
  sui-json --> sui-move-build
  sui-json --> sui-types
  sui-json-rpc --> mysten-metrics
  sui-json-rpc --> sui-config
  sui-json-rpc --> sui-core
  sui-json-rpc --> sui-display
  sui-json-rpc --> sui-json
  sui-json-rpc --> sui-json-rpc-api
  sui-json-rpc --> sui-json-rpc-types
  sui-json-rpc --> sui-macros
  sui-json-rpc --> sui-name-service
  sui-json-rpc --> sui-open-rpc
  sui-json-rpc --> sui-open-rpc-macros
  sui-json-rpc --> sui-protocol-config
  sui-json-rpc --> sui-storage
  sui-json-rpc --> sui-transaction-builder
  sui-json-rpc --> sui-types
  sui-json-rpc --> typed-store-error
  sui-json-rpc-api --> mysten-metrics
  sui-json-rpc-api --> sui-json
  sui-json-rpc-api --> sui-json-rpc-types
  sui-json-rpc-api --> sui-open-rpc
  sui-json-rpc-api --> sui-open-rpc-macros
  sui-json-rpc-api --> sui-types
  sui-json-rpc-tests --> sui-config
  sui-json-rpc-tests --> sui-core
  sui-json-rpc-tests --> sui-json
  sui-json-rpc-tests --> sui-json-rpc
  sui-json-rpc-tests --> sui-json-rpc-api
  sui-json-rpc-tests --> sui-json-rpc-types
  sui-json-rpc-tests --> sui-keys
  sui-json-rpc-tests --> sui-macros
  sui-json-rpc-tests --> sui-move-build
  sui-json-rpc-tests --> sui-open-rpc
  sui-json-rpc-tests --> sui-open-rpc-macros
  sui-json-rpc-tests --> sui-protocol-config
  sui-json-rpc-tests --> sui-sdk
  sui-json-rpc-tests --> sui-simulator
  sui-json-rpc-tests --> sui-swarm-config
  sui-json-rpc-tests --> sui-test-transaction-builder
  sui-json-rpc-tests --> sui-types
  sui-json-rpc-types --> mysten-metrics
  sui-json-rpc-types --> sui-enum-compat-util
  sui-json-rpc-types --> sui-json
  sui-json-rpc-types --> sui-macros
  sui-json-rpc-types --> sui-package-resolver
  sui-json-rpc-types --> sui-protocol-config
  sui-json-rpc-types --> sui-types
  sui-keys --> sui-types
  sui-kv-rpc --> mysten-metrics
  sui-kv-rpc --> mysten-network
  sui-kv-rpc --> sui-data-ingestion-core
  sui-kv-rpc --> sui-kvstore
  sui-kv-rpc --> sui-protocol-config
  sui-kv-rpc --> sui-rpc-api
  sui-kv-rpc --> sui-types
  sui-kvstore --> sui-data-ingestion-core
  sui-kvstore --> sui-types
  sui-light-client --> sui-config
  sui-light-client --> sui-data-ingestion-core
  sui-light-client --> sui-json-rpc-types
  sui-light-client --> sui-package-resolver
  sui-light-client --> sui-rpc-api
  sui-light-client --> sui-sdk
  sui-light-client --> sui-storage
  sui-light-client --> sui-types
  sui-macros --> sui-proc-macros
  sui-metrics-push-client --> mysten-metrics
  sui-metrics-push-client --> sui-tls
  sui-metrics-push-client --> sui-types
  sui-move --> mysten-metrics
  sui-move --> sui-config
  sui-move --> sui-macros
  sui-move --> sui-move-build
  sui-move --> sui-package-alt
  sui-move --> sui-protocol-config
  sui-move --> sui-sdk
  sui-move --> sui-types
  sui-move-build --> mysten-common
  sui-move-build --> sui-package-alt
  sui-move-build --> sui-protocol-config
  sui-move-build --> sui-types
  sui-move-lsp --> sui-move-build
  sui-move-lsp --> sui-package-alt
  sui-move-lsp --> sui-package-management
  sui-move-natives-latest --> sui-protocol-config
  sui-move-natives-latest --> sui-types
  sui-move-natives-v0 --> sui-protocol-config
  sui-move-natives-v0 --> sui-types
  sui-move-natives-v1 --> sui-protocol-config
  sui-move-natives-v1 --> sui-types
  sui-move-natives-v2 --> sui-protocol-config
  sui-move-natives-v2 --> sui-types
  sui-name-service --> sui-types
  sui-network --> mysten-common
  sui-network --> mysten-metrics
  sui-network --> mysten-network
  sui-network --> sui-config
  sui-network --> sui-data-ingestion-core
  sui-network --> sui-http
  sui-network --> sui-macros
  sui-network --> sui-protocol-config
  sui-network --> sui-simulator
  sui-network --> sui-storage
  sui-network --> sui-swarm-config
  sui-network --> sui-tls
  sui-network --> sui-types
  sui-node --> consensus-core
  sui-node --> mysten-common
  sui-node --> mysten-metrics
  sui-node --> mysten-network
  sui-node --> mysten-service
  sui-node --> sui-config
  sui-node --> sui-core
  sui-node --> sui-http
  sui-node --> sui-json-rpc
  sui-node --> sui-json-rpc-api
  sui-node --> sui-macros
  sui-node --> sui-metrics-push-client
  sui-node --> sui-name-service
  sui-node --> sui-network
  sui-node --> sui-protocol-config
  sui-node --> sui-rpc-api
  sui-node --> sui-snapshot
  sui-node --> sui-storage
  sui-node --> sui-telemetry
  sui-node --> sui-tls
  sui-node --> sui-types
  sui-node --> typed-store
  sui-open-rpc --> sui-json
  sui-open-rpc --> sui-json-rpc
  sui-open-rpc --> sui-json-rpc-api
  sui-open-rpc --> sui-json-rpc-types
  sui-open-rpc --> sui-protocol-config
  sui-open-rpc --> sui-types
  sui-oracle --> mysten-metrics
  sui-oracle --> sui-config
  sui-oracle --> sui-json-rpc-types
  sui-oracle --> sui-keys
  sui-oracle --> sui-move-build
  sui-oracle --> sui-sdk
  sui-oracle --> sui-types
  sui-package-alt --> sui-config
  sui-package-alt --> sui-json-rpc-types
  sui-package-alt --> sui-keys
  sui-package-alt --> sui-package-management
  sui-package-alt --> sui-sdk
  sui-package-dump --> sui-types
  sui-package-management --> sui-framework-snapshot
  sui-package-management --> sui-json-rpc-types
  sui-package-management --> sui-protocol-config
  sui-package-management --> sui-sdk
  sui-package-management --> sui-types
  sui-package-resolver --> sui-move-build
  sui-package-resolver --> sui-types
  sui-pg-db --> sui-field-count
  sui-pg-db --> sui-indexer-alt-framework-store-traits
  sui-pg-db --> sui-sql-macro
  sui-proc-macros --> sui-enum-compat-util
  sui-protocol-config --> sui-protocol-config-macros
  sui-proxy --> mysten-metrics
  sui-proxy --> sui-tls
  sui-proxy --> sui-types
  sui-replay --> sui-config
  sui-replay --> sui-core
  sui-replay --> sui-execution
  sui-replay --> sui-framework
  sui-replay --> sui-json-rpc-api
  sui-replay --> sui-json-rpc-types
  sui-replay --> sui-protocol-config
  sui-replay --> sui-sdk
  sui-replay --> sui-storage
  sui-replay --> sui-transaction-checks
  sui-replay --> sui-types
  sui-replay-2 --> sui-config
  sui-replay-2 --> sui-data-store
  sui-replay-2 --> sui-execution
  sui-replay-2 --> sui-framework
  sui-replay-2 --> sui-json-rpc-types
  sui-replay-2 --> sui-move
  sui-replay-2 --> sui-move-build
  sui-replay-2 --> sui-package-alt
  sui-replay-2 --> sui-package-management
  sui-replay-2 --> sui-types
  sui-rosetta --> mysten-metrics
  sui-rosetta --> sui-config
  sui-rosetta --> sui-keys
  sui-rosetta --> sui-move-build
  sui-rosetta --> sui-sdk
  sui-rosetta --> sui-swarm-config
  sui-rosetta --> sui-test-transaction-builder
  sui-rosetta --> sui-types
  sui-rpc-api --> mysten-network
  sui-rpc-api --> sui-config
  sui-rpc-api --> sui-name-service
  sui-rpc-api --> sui-package-resolver
  sui-rpc-api --> sui-protocol-config
  sui-rpc-api --> sui-types
  sui-rpc-benchmark --> sui-futures
  sui-rpc-loadgen --> sui-json-rpc-types
  sui-rpc-loadgen --> sui-keys
  sui-rpc-loadgen --> sui-sdk
  sui-rpc-loadgen --> sui-types
  sui-rpc-resolver --> sui-package-resolver
  sui-rpc-resolver --> sui-rpc-api
  sui-rpc-resolver --> sui-types
  sui-sdk --> mysten-common
  sui-sdk --> sui-config
  sui-sdk --> sui-json
  sui-sdk --> sui-json-rpc-api
  sui-sdk --> sui-json-rpc-types
  sui-sdk --> sui-keys
  sui-sdk --> sui-macros
  sui-sdk --> sui-protocol-config
  sui-sdk --> sui-simulator
  sui-sdk --> sui-transaction-builder
  sui-sdk --> sui-types
  sui-security-watchdog --> mysten-metrics
  sui-simulator --> mysten-network
  sui-simulator --> sui-framework
  sui-simulator --> sui-move-build
  sui-simulator --> sui-types
  sui-single-node-benchmark --> sui-config
  sui-single-node-benchmark --> sui-core
  sui-single-node-benchmark --> sui-macros
  sui-single-node-benchmark --> sui-move-build
  sui-single-node-benchmark --> sui-protocol-config
  sui-single-node-benchmark --> sui-simulator
  sui-single-node-benchmark --> sui-storage
  sui-single-node-benchmark --> sui-test-transaction-builder
  sui-single-node-benchmark --> sui-transaction-checks
  sui-single-node-benchmark --> sui-types
  sui-snapshot --> sui-config
  sui-snapshot --> sui-core
  sui-snapshot --> sui-futures
  sui-snapshot --> sui-protocol-config
  sui-snapshot --> sui-storage
  sui-snapshot --> sui-types
  sui-source-validation --> sui-config
  sui-source-validation --> sui-json-rpc-types
  sui-source-validation --> sui-move-build
  sui-source-validation --> sui-package-alt
  sui-source-validation --> sui-package-management
  sui-source-validation --> sui-sdk
  sui-source-validation --> sui-test-transaction-builder
  sui-source-validation --> sui-types
  sui-storage --> mysten-metrics
  sui-storage --> sui-config
  sui-storage --> sui-json-rpc-types
  sui-storage --> sui-macros
  sui-storage --> sui-protocol-config
  sui-storage --> sui-simulator
  sui-storage --> sui-test-transaction-builder
  sui-storage --> sui-types
  sui-storage --> typed-store
  sui-surfer --> mysten-common
  sui-surfer --> sui-core
  sui-surfer --> sui-json-rpc-types
  sui-surfer --> sui-macros
  sui-surfer --> sui-move-build
  sui-surfer --> sui-protocol-config
  sui-surfer --> sui-simulator
  sui-surfer --> sui-swarm-config
  sui-surfer --> sui-types
  sui-swarm --> mysten-metrics
  sui-swarm --> mysten-network
  sui-swarm --> sui-config
  sui-swarm --> sui-macros
  sui-swarm --> sui-node
  sui-swarm --> sui-protocol-config
  sui-swarm --> sui-swarm-config
  sui-swarm --> sui-tls
  sui-swarm --> sui-types
  sui-swarm-config --> mysten-common
  sui-swarm-config --> sui-config
  sui-swarm-config --> sui-execution
  sui-swarm-config --> sui-genesis-builder
  sui-swarm-config --> sui-macros
  sui-swarm-config --> sui-protocol-config
  sui-swarm-config --> sui-rpc-api
  sui-swarm-config --> sui-types
  sui-synthetic-ingestion --> sui-storage
  sui-synthetic-ingestion --> sui-test-transaction-builder
  sui-synthetic-ingestion --> sui-types
  sui-telemetry --> sui-core
  sui-test-transaction-builder --> sui-genesis-builder
  sui-test-transaction-builder --> sui-move-build
  sui-test-transaction-builder --> sui-sdk
  sui-test-transaction-builder --> sui-types
  sui-tool --> consensus-core
  sui-tool --> mysten-metrics
  sui-tool --> sui-config
  sui-tool --> sui-core
  sui-tool --> sui-data-ingestion-core
  sui-tool --> sui-network
  sui-tool --> sui-package-dump
  sui-tool --> sui-protocol-config
  sui-tool --> sui-replay
  sui-tool --> sui-sdk
  sui-tool --> sui-snapshot
  sui-tool --> sui-storage
  sui-tool --> sui-tls
  sui-tool --> sui-types
  sui-tool --> typed-store
  sui-transaction-builder --> sui-json
  sui-transaction-builder --> sui-json-rpc-types
  sui-transaction-builder --> sui-protocol-config
  sui-transaction-builder --> sui-types
  sui-transaction-checks --> sui-config
  sui-transaction-checks --> sui-execution
  sui-transaction-checks --> sui-macros
  sui-transaction-checks --> sui-protocol-config
  sui-transaction-checks --> sui-types
  sui-transactional-test-runner --> sui-config
  sui-transactional-test-runner --> sui-core
  sui-transactional-test-runner --> sui-framework
  sui-transactional-test-runner --> sui-framework-snapshot
  sui-transactional-test-runner --> sui-graphql-rpc
  sui-transactional-test-runner --> sui-json-rpc
  sui-transactional-test-runner --> sui-json-rpc-api
  sui-transactional-test-runner --> sui-json-rpc-types
  sui-transactional-test-runner --> sui-protocol-config
  sui-transactional-test-runner --> sui-rpc-api
  sui-transactional-test-runner --> sui-storage
  sui-transactional-test-runner --> sui-swarm-config
  sui-transactional-test-runner --> sui-types
  sui-transactional-test-runner --> typed-store
  sui-types --> consensus-config
  sui-types --> consensus-types
  sui-types --> mysten-common
  sui-types --> mysten-metrics
  sui-types --> mysten-network
  sui-types --> sui-enum-compat-util
  sui-types --> sui-macros
  sui-types --> sui-protocol-config
  sui-types --> typed-store-error
  sui-upgrade-compatibility-transactional-tests --> sui-move-build
  sui-verifier-latest --> sui-protocol-config
  sui-verifier-latest --> sui-types
  sui-verifier-transactional-tests --> sui-transactional-test-runner
  sui-verifier-v0 --> sui-protocol-config
  sui-verifier-v0 --> sui-types
  sui-verifier-v1 --> sui-types
  sui-verifier-v2 --> sui-protocol-config
  sui-verifier-v2 --> sui-types
  typed-store --> mysten-common
  typed-store --> mysten-metrics
  typed-store --> sui-macros
  typed-store --> typed-store-derive
  typed-store --> typed-store-error
  typed-store --> typed-store-workspace-hack
